export const WeeklyData = [
  {
    name: "test1",
    id: 1,
    price: "0",
    user: "10",
    project: "20",
    allowed: "false",
    state: "Weekly-Free",
  },
  {
    name: "test2",
    id: 2,
    price: "70",
    user: "5",
    project: "7",
    allowed: "true",
    state: "Weekly-Premium1",
  },
  {
    id: 3,
    name: "test2",
    price: "100",
    user: "10",
    project: "15",
    allowed: "true",
    state: "Weekly-Premium2",
  },
];
export const MonthlyData = [
  {
    name: "test1",
    id: 1,
    price: "0",
    user: "10",
    project: "20",
    allowed: "false",
    state: "Monthly-Free",
  },
  {
    name: "test2",
    id: 2,
    price: "70",
    user: "5",
    project: "7",
    allowed: "true",
    state: "Monthly-Premium1",
  },
  {
    id: 3,
    name: "test2",
    price: "100",
    user: "10",
    project: "15",
    allowed: "true",
    state: "Monthly-Premium2",
  },
];
export const YearlyData = [
  {
    name: "test1",
    id: 1,
    price: "0",
    user: "10",
    project: "20",
    allowed: "false",
    state: "Yearly-Free",
  },
  {
    name: "test2",
    id: 2,
    price: "70",
    user: "5",
    project: "7",
    allowed: "true",
    state: "Yearly-Premium1",
  },
  {
    id: 3,
    name: "test2",
    price: "100",
    user: "10",
    project: "15",
    allowed: "true",
    state: "Yearly-Premium2",
  },
];
